### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lasley** [trobz/openerp-web-unleashed#11]
What license is this module released under? 

Can you please add a license file to the repo and/or to the keys of the manifest files?

LGPL-3 is my preferred for web stuff.

**Comment by sbevnc** [comment]
Hi @lasley .
We published this on Odoo app store so you can have a look at [here](https://apps.openerp.com/apps/modules/8.0/web_unleashed/).
The license is Affero GPL-3.

Thank you.

**Comment by lasley** [comment]
Thanks @sbevnc!
