### ISSUE TITLE
Are OpenERP widget supported in this kind of view ?

### ISSUE THREAD

**Issue by njeudy** [trobz/openerp-web-unleashed#4]
One more questions :)
- If my model use many2one field, can I use m2o widget like OpenERP Form or do I need to define all from scratch ?

**Comment by zazabe** [comment]
HI,

For the [dashboard](https://github.com/trobz/openerp-dashboard) project, I was able to [reuse some basic OpenERP widgets in my code](https://github.com/trobz/openerp-dashboard/blob/master/dashboard/static/src/js/views/search/widgets.js).

You can override some OpenERP widget methods to make them behave like a real Backbone view, it's work well for a `DateTimeWidget` for example, but I was not able to do the same for a many2one widget... 

Actually I didn't try so much for many2one but I think you will have to dive deeply in OpenERP sources and override lot of things...

I'm interested if you can do it successfully :)
