### ISSUE TITLE
Is this planned to be ported for odoo v8?

### ISSUE THREAD

**Issue by ashnur** [trobz/openerp-web-unleashed#5]

**Comment by zazabe** [comment]
Yes, we are working on it... should be pushed within this week (hope so) ;)

**Comment by zazabe** [comment]
sorry, we took more time because we are working on the migration of the booking chart at the same time... hope we can publish it at the beginning of the next month, with the booking chart too.

**Comment by ilexius** [comment]
I'm developing a few custom views for Odoo 8 + 9 atm, it would be amazing to use this library for it!

**Comment by zazabe** [comment]
done, at least for version 8.0, we didn't have tested it yet on the odoo `master` branch but it may works too.
