### ISSUE TITLE
Why other copies of Backbone and Underscore are included?

### ISSUE THREAD

**Issue by alhashash** [trobz/openerp-web-unleashed#6]
The web module already loads these. Is it a version issue?

**Comment by sbevnc** [comment]
It's not a version issue. Backbone and Underscore are already included in OpenERP, but they are using old version. Unleashed include the latest version of these libraries in noConflict mode.

You can have a look at the documentation.

**Comment by alhashash** [comment]
Thanks a lot for the explanation. I missed that part in the documentation. I got confused as Odoo v8 uses the same Backbone version (1.1) and a later Underscore version (1.6 vs 1.5.2 in  openerp-web-unleashed).

**Comment by sbevnc** [comment]
thank you for your feedback, we updated our source code.
