### ISSUE TITLE
An error occurred while trying to test

### ISSUE THREAD

**Issue by VbossEkat** [trobz/openerp-web-unleashed#8]
You have created an interesting module, and I decided to test it , but faced with the following error . What could be wrong in my actions ?. Tell me please.

![odoo_modul_todo_error](https://cloud.githubusercontent.com/assets/11025283/11619604/b6cabb46-9ccb-11e5-9a31-652c3a35a797.png)

**Comment by sbevnc** [comment]
@VbossEkat:
- which version of Odoo and which browser did you use for the test?
- could you please turn on debugging mode on your application and give us the **stack trace** or  **console log**? we need more information about the bug.

**Comment by VbossEkat** [comment]
Thanks for the answer. 
Here the requested data :
1. Version 8.0-20151014
2. I put the file
[odoo-server_to_send.log.txt](https://github.com/trobz/openerp-web-unleashed/files/56514/odoo-server_to_send.log.txt)

**Comment by VbossEkat** [comment]
[odoo error load modul 20151209.zip.txt](https://github.com/trobz/openerp-web-unleashed/files/56571/odoo.error.load.modul.20151209.zip.txt)

Update : After installing the module , part of the data is no longer displayed . This behavior is similar to the module demo_todo

**Comment by VbossEkat** [comment]
![odoo_modul_todo_error 20151209](https://cloud.githubusercontent.com/assets/11025283/11683501/0df1bea2-9e8d-11e5-9969-d3046d8751eb.png)

**Comment by sbevnc** [comment]
and in your firefox browser, can you send us your **console** log ?

it will look like below:
![image](https://cloud.githubusercontent.com/assets/6452983/11707261/862af5b2-9f34-11e5-8153-0021015fbeba.png)

**Comment by VbossEkat** [comment]
I believe that I understand ....
[odoo error load modul 20151210.mp4.txt](https://github.com/trobz/openerp-web-unleashed/files/57771/odoo.error.load.modul.20151210.mp4.txt)

**Comment by VbossEkat** [comment]
[odoo error load modul 20151210_1.mp4.txt](https://github.com/trobz/openerp-web-unleashed/files/57821/odoo.error.load.modul.20151210_1.mp4.txt)

**Comment by sbevnc** [comment]
OK, we are working on your the error.

**Comment by VbossEkat** [comment]
Thank you. Waiting . If they need additional information for debugging - ready to help.

**Comment by VbossEkat** [comment]
Hello , you need my help?

**Comment by sbevnc** [comment]
Hello, we  have tested with latest source code from `odoo` branch `8.0`, `openerp-web-unleashed` branch `8.0` and latest version from Firefox, but we could not re-produce your issue (although tried with both Firefox and Chrome).
- Here is the video of the step we tried to reproduce: [Odoo-Test-Screencast.webm.txt](https://github.com/trobz/openerp-web-unleashed/files/72153/Untitled.Screencast.webm.txt)
- One thing you can try now is:
  - re-install with fresh database with no module installed.
  - install some pure modules from Odoo and finally install `web-unleashed`, `web_unleashed_extra` and `demo_todo`.
  - if you have some custom modules, try not to install them to identify the source of error.
- if you have more information about the bug, please keep sending them to us to fix.

regards
