### ISSUE TITLE
Error Javascript

### ISSUE THREAD

**Issue by cunguito** [trobz/openerp-web-unleashed#9]
Cannot read property 'module' of undefined.

/\* /booking_chart/static/src/js/widgets/chart.js defined in bundle 'web.assets_backend' */
openerp.unleashed.module('booking_chart').(...)

**Comment by sbevnc** [comment]
The issue has been fixed in https://github.com/trobz/openerp-booking-chart repository, please pull the latest source code from this repository to apply the fix.

Thank you for reporting the bug.
